export const wwTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres": '',
    "Planted": '',
    "cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Sample Date": '',
    "Sample Description (PO, SLT, FM, PD)": '',
    "Sample Data": '',
    "Source": '',
    "N (PPM)": '',
    "NH4- N": '',
    "NH3-N": '',
    "NO3- N": '',
    "P (PPM)": '',
    "K (PPM)": '',
    "Calcium": '',
    "Magnesium": '',
    "SodiumBiCarb": '',
    "Carbonate": '',
    "Sulfate": '',
    "Chloride": '',
    "EC (μmhos/cm)": '',
    "TDS (mg/L)": '',
    "KN DL (mg/L)": '',
    "NH4-N DL": '',
    "NH3-N DL": '',
    "NO3-N DL": '',
    "P DL": '',
    "K DL": '',
    "Calcium DL": '',
    "Magnesium DL": '',
    "Sodium DlBiCarb DL": '',
    "Carbonate DL": '',
    "Sulfate DL": '',
    "Chloride DL": '',
    "EC DL (μmhos/cm)": '',
    "TDS DL (mg/L)": '',
    "pH ": '',
    "Application Description": '',
    "Material Type": '',
    "Application Rate (GPM)": '',
    "Run Time (Hours)": '',
    "Total Gallons Applied": '',
    "Application Rate per acre (Gallons/ acre)": ''
}

export const fwTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres ": '',
    "Planted": '',
    "cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Sample Date": '',
    "Source Description (IW,C,R,D)": '',
    "Source Type": '',
    "Sample Desc": '',
    "Source of Analysis": '',
    "Nitrogen (mg/ L)": '',
    "Ammonium- N": '',
    "Nitrite- N": '',
    "Calcium": '',
    "Magnesium": '',
    "SodiumBiCarbonate": '',
    "Carbonate": '',
    "SulfateChloride": '',
    "EC": '',
    "TDS": '',
    "Nitrogen DL": '',
    "Ammonium-N DL": '',
    "Nitrite-N DL": '',
    "Calcium DL": '',
    "Magnesium DL ": '',
    "Sodium DL": '',
    "BiCarbonate DL": '',
    "Carbonate DL": '',
    "Sulfate DL": '',
    "Chloride DL": '',
    "EC DL (μmhos/cm)": '',
    "TDS DL (mg/L)": '',
    "Application Rate (GPM)": '',
    "Run Time (Hours) ": '',
    "Total Gallons Applied": '',
    "Application Rate per acre (Gallons/acre)": '',
    "Lbs/Acre N": ''
}


export const smTemplate = {
    "*Application Date": '',
    "Field": '',
    "Acres ": '',
    "Planted": '',
    "cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Sample Date": '',

    "Sample Description": '',
    "Source Description": '',
    "Material Type": '',
    "Source of Analysis": '',
    "Method of Reporting": '',
    "Application (Tons)": '',
    "Application Rate per acre (Tons/acre)": '',
    "% Moisture": '',
    "% N": '',
    "% P": '',
    "% K": '',
    "Calcium": '',
    "Magnesium": '',
    "Sodium": '',
    "Sulfur": '',
    "Chloride": '',
    "% TFS ": '',
    "N DL ": '',
    "P DL": '',
    "K DL": '',
    "Calcium DL": '',
    "Magnesium DL": '',
    "Sodium DL": '',
    "Sulfur DL": '',
    "Chloride DL": '',
    "TFS  DL": '',
}

export const cfTemplate = {
    "*Application Date": '',
    "Field": '',
    "Acres ": '',
    "Planted": '',
    "cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',

    "Import Description": '',
    "Import Date": '',
    "Material Type": '',
    "Amount Imported (tons/ gals)": '',
    "Method of Reporting": '',
    "Application Rate (Lbs/Acre)": '',
    "Amount applied ": '',
    "% Moisture": '',
    "% N": '',
    "% P": '',
    "% K": '',
    "% Salt/ TFS/ TDS": '',
}


export const smExportTemplate = {
    "Date last hauled": '',
    "Operator Name": '',
    "Operator Phone": '',
    "Operator 2nd Phone": '',
    "Operator Street": '',
    "Operator City": '',
    "Operator State": '',
    "Operator Zip": '',
    "Operator Is Owner": '',
    "Operator": '',
    "Responsible for Fees": '',
    "Contact First": '',
    "Contact Phone": '',
    "Hauler": '',
    "Hauler First": '',
    "Hauler Phone": '',
    "Hauler Street": '',
    "Hauler Cross Street": '',
    "Hauler County": '',
    "Hauler City": '',
    "Hauler State": '',

    "Hauler Zip": '',
    "Recipient": '',
    "Destination Type": '',
    "Recipient Phone": '',
    "Recipient Street": '',
    "Recipient Cross Street": '',
    "Recipient County": '',
    "Recipient City": '',
    "Recipient State": '',
    "Recipient Zip": '',
    "APN": '',
    "Destination Street": '',
    "Destination Cross Street": '',
    "Destination County": '',
    "Destination City": '',
    "Destination State": '',
    "Destination Zip": '',
    "Method used to determine amount hauled:": '',
    "Reporting Method": '',
    "Material Type": '',
    "Amount (Tons)": '',
    "% Moisture": '',
    "% N": '',
    "% P": '',
    "% K": '',
    "% TFS": '',
}


export const wwExportTemplate = {
    "Date last hauled": '',
    "Operator Name": '',
    "Operator Phone": '',
    "Operator 2nd Phone": '',
    "Operator Street": '',
    "Operator City": '',
    "Operator State": '',
    "Operator Zip": '',
    "Operator Is Owner": '',
    "Operator": '',
    "Responsible for Fees": '',
    "Contact First": '',
    "Contact Phone": '',
    "Hauler": '',
    "Hauler First": '',
    "Hauler Phone": '',
    "Hauler Street": '',
    "Hauler Cross Street": '',
    "Hauler County": '',
    "Hauler City": '',
    "Hauler State": '',
    "Hauler Zip": '',
    "Recipient": '',
    "Destination Type": '',
    "Recipient Phone": '',
    "Recipient Street": '',
    "Recipient Cross Street": '',
    "Recipient County": '',
    "Recipient City": '',
    "Recipient State": '',
    "Recipient Zip": '',
    "APN": '',
    "Destination Street": '',
    "Destination Cross Street": '',
    "Destination County": '',
    "Destination City": '',
    "Destination State": '',
    "Destination Zip": '',
    "Method used to determine amount hauled:": '',
    "Reporting Method": '',
    "Material Type": '',
    "Hours": '',
    "GPM": '',
    "Amount (Gallons)": '',
    "Source Description": '',
    "N (PPM)": '',
    "P (PPM)": '',
    "K (PPM)": '',
    "EC (umhos/cm)": '',
    "TDS (mg/L)": '',
}


export const soilTemplate = {
    "Application Date": '',
    "*Field": '',
    "*Acres": '',
    "Planted": '',
    "cropable": '',
    "Total Acres": '',
    "*Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "": '',
    "Source Desc": '',
    "Sample Date": '',
    "": '',
    "Sample Description": '',
    "Source of Analysis": '',
    "Nitrate-N (mg/Kg)": '',
    "P": '',
    "Sol. P": '',
    "": '',
    "K": '',
    "EC (μmhos/cm)": '',
    "Organic Matter (%)": '',
    "Nitrate-N DL (mg/ kg)": '',
    "Total": '',
    "P DL": '',
    "Soluble Phosphorus DL": '',
    "Potassium DL": '',
    "EC DL (μmhos/cm)": '',
    "Organic Matter DL (%)": '',
    "Sample Date": '',
    "Sample Description": '',
    "Source of Analysis": '',
    "Nitrate-N (mg/L)": '',
    "P": '',
    "Sol. P": '',
    "K": '',
    "EC": '',
    "Organic Matter": '',
    "Nitrate-N DL (mg/ L)": '',
    "Total P DL": '',
    "Soluble Phosphorus DL": '',
    "Potassium DL": '',
    "EC DL": '',
    "Organic Matter DL": '',
    "Sample Date": '',
    "Sample Description": '',
    "Source of Analysis": '',
    "Nitrate-N (mg/L)": '',
    "P": '',
    "Sol. P": '',
    "K": '',
    "EC": '',
    "Organic Matter": '',
    "Nitrate-N DL (mg/ L)": '',
    "Total P DL": '',
    "Soluable Phosphorus DL": '',
    "Potassium DL": '',
    "EC DL": '',
    "Organic Matter DL": '',
}


export const plowdownTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres": '',
    "Planted": '',
    "cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Source": '',
    "Desc": '',
    "N lbs/ acre": '',
    "P lbs/ acre": '',
    "K lbs/ acre": '',
    "Salt  lbs/ acre": '',
}

export const tiledrainageTemplate = {
    "Source Description": '',
    "Sample Date": '',
    "Sample Description": '',
    "Source of Analysis": '',
    "Ammonium-N (mg/ L)": '',
    "Nitrate-N": '',
    "P": '',
    "EC (μmhos/cm)": '',
    "TDS (mg/ L)": '',
    "Ammonium-N DL (mg/ L)": '',
    "Nitrate-N DL": '',
    "P DL": '',
    "EC DL (μmhos/cm)": '',
    "TDS DL (mg/ L)": '',
}


export const dischargeTemplate = {
    "Type": '',
    "Date Time": '',
    "Location": '',
    "Volume discharged": '',
    "Volume Unit": '',
    "Duration of Discharge (mins)": '',
    "Discharge Source": '',
    "Method of Measuring": '',
    "Rationale for Sample Location": '',
    "Reference Number for Discharge Site": '',
}