/** In order for Templates to work:
 * 
 *  Header names in the sheet must not change.
 *  These names must be referenced in code which is sensitive to typos
 *      - Extracting the needed data requires the code to know the header name
 *      - Eg when needing the field, it must be found under row['Field']
 *          - Any mispelling of the key wil break the system.
 * 
 * Benefits:
 *  - Order of columns doesnt matter
 *  - Missing columns will have default value
 *      - This makes is more flexible to add or remove columns
 * 
 * 
 * Considerations:
 * 
 *  - Sheet owners and program must agree on Header Name
 *  - Sheet will still require information to create and find: Fields, Crops, Field Crops, Field Crop Applications
 * 
 */



const wwTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres Planted": '',
    "Cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Sample Date": '',
    "Sample Description": '',
    "Sample Data Source": '',
    "N (mg/L)": '0',
    "NH4-N (mg/L)": '0',
    "NH3-N (mg/L)": '0',
    "NO3-N (mg/L)": '0',
    "P (mg/L)": '0',
    "K (mg/L)": '0',
    "Calcium (mg/L)": '0',
    "Magnesium (mg/L)": '0',
    "Sodium (mg/L)": '0',
    "BiCarb (mg/L)": '0',
    "Carbonate (mg/L)": '0',
    "Sulfate (mg/L)": '0',
    "Chloride (mg/L)": '0',
    "EC (umhos/cm)": '0',
    "TDS (mg/L)": '0',
    "N DL": '0.5',
    "NH4-N DL": '0.5',
    "NH3-N DL": '0.5',
    "NO3-N DL": '0.5',
    "P DL": '0.5',
    "K DL": '0.5',
    "Calcium DL": '0.5',
    "Magnesium DL": '0.5',
    "Sodium DL": '0.5',
    "BiCarb DL": '0.5',
    "Carbonate DL": '0.5',
    "Sulfate DL": '0.5',
    "Chloride DL": '0.5',
    "EC DL": '0.5',
    "TDS DL": '0.5',
    "PH": '0',
    "Application Description": '',
    "Material Type": '',
    "Application Rate (GPM)": '0',
    "Run Time (Hours)": '0',
    "Total Gallons Applied": '0',
    "Application Rate per acre (Gallons/ acre)": '0'
}

const fwTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres Planted": '',
    "Cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Sample Date": '',
    "Source Description": '',
    "Source Type": '',
    "Sample Description": '',
    "Source of Analysis": '',
    "N (mg/L)": '',
    "NH4-N (mg/L)": '',
    "NO3-N (mg/L)": '',
    "Calcium (mg/L)": '',
    "Magnesium (mg/L)": '',
    "Sodium (mg/L)": '',
    "BiCarb (mg/L)": '',
    "Carbonate (mg/L)": '',
    "Sulfate (mg/L)": '',
    "Chloride (mg/L)": '',
    "EC (umhos/cm)": '',
    "TDS (mg/L)": '',
    "N DL": '0.5',
    "NH4-N DL": '0.5',
    "NO3-N DL": '0.5',
    "Calcium DL": '0.5',
    "Magnesium DL": '0.5',
    "Sodium DL": '0.5',
    "BiCarb DL": '0.5',
    "Carbonate DL": '0.5',
    "Sulfate DL": '0.5',
    "Chloride DL": '0.5',
    "EC DL": '0.5',
    "TDS DL": '0.5',
    "Application Rate (GPM)": '',
    "Run Time (Hours)": '',
    "Total Gallons Applied": '',
    "Application Rate per Acre (Gallons/acre)": '',
}

const smTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres Planted": '',
    "Cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Sample Date": '',
    "Sample Description": '',
    "Source Description": '',
    "Material Type": '',
    "Source of Analysis": '',
    "Method of Reporting": '',
    "Application (Tons)": '',
    "Application Rate per Acre (Tons/acre)": '',
    "% Moisture": '',
    "% N": '',
    "% P": '',
    "% K": '',
    "% Calcium": '',
    "% Magnesium": '',
    "% Sodium": '',
    "% Sulfur": '',
    "% Chloride": '',
    "% TFS": '',
    "N DL": '',
    "P DL": '',
    "K DL": '',
    "Calcium DL": '',
    "Magnesium DL": '',
    "Sodium DL": '',
    "Sulfur DL": '',
    "Chloride DL": '',
    "TFS DL": '',
}

const cfTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres Planted": '',
    "Cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Import Description": '',
    "Import Date": '',
    "Material Type": '',
    "Amount Imported (tons/ gals)": '',
    "Method of Reporting": '',
    "Application Rate (Lbs/Acre)": '',
    "Amount Applied": '',
    "% Moisture": '',
    "% N": '',
    "% P": '',
    "% K": '',
    "% Salt/ TFS/ TDS": '',
}


const smExportTemplate = {
    "Date": '',
    "Operator Name": '',
    "Operator Phone": '',
    "Operator 2nd Phone": '',
    "Operator Street": '',
    "Operator City": '',
    "Operator State": '',
    "Operator Zip": '',
    "Operator Is Owner": '',
    "Operator Responsible for Fees": '',
    "Contact First": '',
    "Contact Phone": '',
    "Hauler": '',
    "Hauler First": '',
    "Hauler Phone": '',
    "Hauler Street": '',
    "Hauler Cross Street": '',
    "Hauler County": '',
    "Hauler City": '',
    "Hauler State": '',
    "Hauler Zip": '',
    "Recipient": '',
    "Destination Type": '',
    "Recipient Phone": '',
    "Recipient Street": '',
    "Recipient Cross Street": '',
    "Recipient County": '',
    "Recipient City": '',
    "Recipient State": '',
    "Recipient Zip": '',
    "APN": '',
    "Destination Street": '',
    "Destination Cross Street": '',
    "Destination County": '',
    "Destination City": '',
    "Destination State": '',
    "Destination Zip": '',
    "Method Used to Determine Amount Hauled": '',
    "Reporting Method": '',
    "Material Type": '',
    "Amount (Tons)": '',
    "% Moisture": '',
    "% N": '',
    "% P": '',
    "% K": '',
    "% TFS": '',
}


const wwExportTemplate = {
    "Date": '',
    "Operator Name": '',
    "Operator Phone": '',
    "Operator 2nd Phone": '',
    "Operator Street": '',
    "Operator City": '',
    "Operator State": '',
    "Operator Zip": '',
    "Operator Is Owner": '',
    "Operator Responsible for Fees": '',
    "Contact First": '',
    "Contact Phone": '',
    "Hauler": '',
    "Hauler First": '',
    "Hauler Phone": '',
    "Hauler Street": '',
    "Hauler Cross Street": '',
    "Hauler County": '',
    "Hauler City": '',
    "Hauler State": '',
    "Hauler Zip": '',
    "Recipient": '',
    "Destination Type": '',
    "Recipient Phone": '',
    "Recipient Street": '',
    "Recipient Cross Street": '',
    "Recipient County": '',
    "Recipient City": '',
    "Recipient State": '',
    "Recipient Zip": '',
    "APN": '',
    "Destination Street": '',
    "Destination Cross Street": '',
    "Destination County": '',
    "Destination City": '',
    "Destination State": '',
    "Destination Zip": '',
    "Method Used to Determine Amount Hauled": '',
    "Material Type": '',
    "Hours": '',
    "GPM": '',
    "Amount (Gals)": '',
    "Source Description": '',
    "N (PPM)": '',
    "P (PPM)": '',
    "K (PPM)": '',
    "EC (umhos/cm)": '',
    "TDS (mg/L)": '',
}


const soilTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres Planted": '',
    "Cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Source Description": '',

    "Sample Date1": '',
    "Sample Description1": '',
    "Source of Analysis1": '',
    "N1 (mg/Kg)": '',
    "P1 (mg/Kg)": '',
    "Sol P1 (mg/Kg)": '',
    "K1 (mg/Kg)": '',
    "EC1 (umhos/cm)": '',
    "Organic Matter1 (%)": '',
    "N1 DL": '',
    "P1 DL": '',
    "Sol P1 DL": '',
    "K1 DL": '',
    "EC1 DL": '',
    "Organic Matter1 DL": '',

    "Sample Date2": '',
    "Sample Description2": '',
    "Source of Analysis2": '',
    "N2 (mg/Kg)": '',
    "P2 (mg/Kg)": '',
    "Sol P2 (mg/Kg)": '',
    "K2 (mg/Kg)": '',
    "EC2 (umhos/cm)": '',
    "Organic Matter2 (%)": '',
    "N2 DL": '',
    "P2 DL": '',
    "Sol P2 DL": '',
    "K2 DL": '',
    "EC2 DL": '',
    "Organic Matter2 DL": '',

    "Sample Date3": '',
    "Sample Description3": '',
    "Source of Analysis3": '',
    "N3 (mg/Kg)": '',
    "P3 (mg/Kg)": '',
    "Sol P3 (mg/Kg)": '',
    "K3 (mg/Kg)": '',
    "EC3 (umhos/cm)": '',
    "Organic Matter3 (%)": '',
    "N3 DL": '',
    "P3 DL": '',
    "Sol P3 DL": '',
    "K3 DL": '',
    "EC3 DL": '',
    "Organic Matter3 DL": '',
}


const plowdownTemplate = {
    "Application Date": '',
    "Field": '',
    "Acres Planted": '',
    "Cropable": '',
    "Total Acres": '',
    "Crop": '',
    "Plant Date": '',
    "Rain Day Prior to Event": '',
    "Rain Day of Event": '',
    "Rain Day After Event": '',
    "App Method": '',
    "Source Description": '',
    "N lbs/ acre": '',
    "P lbs/ acre": '',
    "K lbs/ acre": '',
    "Salt lbs/ acre": '',
}

const tiledrainageTemplate = {
    "Source Description": '',
    "Sample Date": '',
    "Sample Description": '',
    "Source of Analysis": '',
    "NH4-N (mg/L)": '',
    "NO3-N (mg/L)": '',
    "P (mg/L)": '',
    "EC (umhos/cm)": '',
    "TDS (mg/L)": '',
    "NH4-N DL": '',
    "NO3-N DL": '',
    "P DL": '',
    "EC DL": '',
    "TDS DL": '',
}


const dischargeTemplate = {
    "Type": '',
    "Date Time": '',
    "Location": '',
    "Volume discharged": '',
    "Volume Unit": '',
    "Duration of Discharge (mins)": '',
    "Discharge Source": '',
    "Method of Measuring": '',
    "Rationale for Sample Location": '',
    "Reference Number for Discharge Site": '',
}

const harvestTemplate = {
    'Field': '',
    'Acres Planted': '',
    'Cropable': '',
    'Total Acres': '',
    'Crop': '',
    'Plant Date': '',
    'Harvest Dates': '',
    'Expected Yield Tons/Acre': '',
    'Actual Yield Tons/Acre': '',
    'Actual Yield Total Tons': '',
    'Sample Date': '',
    'Source of Analysis': '',
    'Reporting Method': '',
    '% Moisture': '',
    '% N': '',
    '% P': '',
    '% K': '',
    '% TFS Salt (Dry Basis)': '',
    'N DL': '',
    'P DL': '',
    'K DL': '',
    'TFS DL': '',
}


export {
    harvestTemplate, wwTemplate, fwTemplate, smTemplate, cfTemplate, smExportTemplate,
    wwExportTemplate, soilTemplate, plowdownTemplate, tiledrainageTemplate, dischargeTemplate
}